-- 코드를 입력하세요
SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    (30*C.DAILY_FEE*(100-REGEXP_REPLACE(P.DISCOUNT_RATE, '[^0-9]+', ''))/100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C, 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND (30*C.DAILY_FEE*(100-REGEXP_REPLACE(P.DISCOUNT_RATE, '[^0-9]+', ''))/100)
        BETWEEN 500000 AND 2000000
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC
