-- I.SEX_UPON_INTAKE은 중성화되지 않았지만
-- O.SEX_UPON_OUTCOME은 중성화된
-- 동물 아이디, 생물 종, 이름 조회를 아이디 순으로
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' 
    AND (O.SEX_UPON_OUTCOME LIKE '%Spayed%' OR O.SEX_UPON_OUTCOME LIKE '%Neutered%')
ORDER BY I.ANIMAL_ID
    