SELECT 
    H.HISTORY_ID, 
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 
            THEN (DATEDIFF(H.END_DATE, H.START_DATE)+1)*C.DAILY_FEE*
            (SELECT 100-REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]', '')
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')/100
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 
            THEN (DATEDIFF(H.END_DATE, H.START_DATE)+1)*C.DAILY_FEE*
            (SELECT 100-REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]', '')
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')/100
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 
            THEN (DATEDIFF(H.END_DATE, H.START_DATE)+1)*C.DAILY_FEE*
            (SELECT 100-REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]', '')
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')/100
        ELSE (DATEDIFF(H.END_DATE, H.START_DATE)+1)*C.DAILY_FEE
        END
    AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID 
WHERE C.CAR_TYPE = '트럭'    
ORDER BY FEE DESC, H.HISTORY_ID DESC