-- 코드를 입력하세요
SELECT H.HISTORY_ID,
CASE WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 7 THEN 
C.DAILY_FEE*(DATEDIFF(H.END_DATE,H.START_DATE)+1) 

WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 BETWEEN 7 AND 29 THEN 
ROUND((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE='트럭' AND DURATION_TYPE = '7일 이상'))*C.DAILY_FEE*(DATEDIFF(H.END_DATE,H.START_DATE)+1)/100, 0)

WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 BETWEEN 30 AND 89 THEN
ROUND((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE='트럭' AND DURATION_TYPE = '30일 이상'))*C.DAILY_FEE*(DATEDIFF(H.END_DATE,H.START_DATE)+1)/100, 0)

WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 90 THEN 
ROUND((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE='트럭' AND DURATION_TYPE = '90일 이상'))*C.DAILY_FEE*(DATEDIFF(H.END_DATE,H.START_DATE)+1)/100, 0)
END AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H, 
CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P

WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE AND
C.CAR_TYPE = '트럭' 

GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC
